"""initial database schema

Revision ID: 1e0b0dc4f480
Revises: 
Create Date: 2025-10-14 03:09:22.666982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0b0dc4f480'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable UUID extension
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Google OAuth email address (unique identifier)'),
    sa.Column('google_id', sa.String(length=255), nullable=False, comment='Google OAuth user ID (sub claim from JWT)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='User display name'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='User avatar URL (from Google profile)'),
    sa.Column('role', sa.String(length=20), server_default='MEMBER', nullable=False, comment='User role: MEMBER (regular user) or ADMIN (administrator)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    comment='User accounts authenticated via Google OAuth 2.0'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('events',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Event title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Event description (optional)'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Event start time (UTC)'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Event end time (UTC)'),
    sa.Column('grace_period_minutes', sa.Integer(), server_default='5', nullable=False, comment='Minutes after start_time before marking as LATE (default: 5)'),
    sa.Column('google_event_id', sa.String(length=255), nullable=False, comment='Google Calendar Event ID (unique identifier from Google API)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this event (NULL for system-synced events)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.CheckConstraint('end_time > start_time', name='check_event_time_range'),
    sa.CheckConstraint('grace_period_minutes >= 0 AND grace_period_minutes <= 60', name='check_grace_period_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Events synced from Google Calendar requiring attendance tracking'
    )
    op.create_index(op.f('ix_events_google_event_id'), 'events', ['google_event_id'], unique=True)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_table('attendance',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who has this attendance record'),
    sa.Column('event_id', sa.UUID(), nullable=False, comment='Event this attendance is for'),
    sa.Column('status', sa.String(length=20), server_default='ABSENT', nullable=False, comment='Attendance status: PRESENT, LATE, ABSENT, LEAVE, MAKEUP, EARLY_LEAVE'),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True, comment='Actual check-in timestamp (NULL for ABSENT/LEAVE)'),
    sa.Column('note', sa.Text(), nullable=True, comment='Additional notes (reason for makeup/leave)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Attendance records linking users to events with status tracking'
    )
    op.create_index('idx_unique_user_event_active', 'attendance', ['user_id', 'event_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_attendance_event_id'), 'attendance', ['event_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False, comment='Type: SICK, PERSONAL, OFFICIAL, OTHER'),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active record)'),
    sa.CheckConstraint("(status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL) OR (status IN ('APPROVED', 'REJECTED') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)", name='check_leave_review_consistency'),
    sa.CheckConstraint('end_time >= start_time', name='check_leave_time_range'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Leave applications with approval workflow'
    )
    op.create_index(op.f('ix_leave_requests_event_id'), 'leave_requests', ['event_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_table('makeup_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active record)'),
    sa.CheckConstraint("(status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL) OR (status IN ('APPROVED', 'REJECTED') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)", name='check_makeup_review_consistency'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Makeup (補簽) applications for missed check-ins'
    )
    op.create_index(op.f('ix_makeup_requests_event_id'), 'makeup_requests', ['event_id'], unique=False)
    op.create_index(op.f('ix_makeup_requests_status'), 'makeup_requests', ['status'], unique=False)
    op.create_index(op.f('ix_makeup_requests_user_id'), 'makeup_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_makeup_requests_user_id'), table_name='makeup_requests')
    op.drop_index(op.f('ix_makeup_requests_status'), table_name='makeup_requests')
    op.drop_index(op.f('ix_makeup_requests_event_id'), table_name='makeup_requests')
    op.drop_table('makeup_requests')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_event_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_event_id'), table_name='attendance')
    op.drop_index('idx_unique_user_event_active', table_name='attendance', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('attendance')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_google_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
